apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ratedo/ks.git'
    targetRevision: HEAD
    path: charts/app-chart  # Путь до папки с Chart.yaml
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc' # Деплоим в тот же кластер, где Argo
    namespace: default
  syncPolicy:
    automated:
      prune: true    # Удалять ресурсы, которых нет в Git
      selfHeal: true # Если ты вручную что-то удалишь через kubectl, Argo вернет это на место
