replicaCount: 1

backend:
  image: ratedo/lab-backend:v1
  port: 8000

nginx:
  image: nginx:1.27
  service:
    type: LoadBalancer
    port: 80

# Эти данные нужны здесь для формирования DATABASE_URL в web.yaml
postgres:
  user: "appuser"
  password: "apppass"
  dbName: "appdb"
  port: 5432
