apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    events { worker_connections 1024; }
    http {
        upstream fastapi_backend {
            server unix:/tmp/uvicorn.sock;
        }
        server {
            listen 80;
            location / {
                proxy_pass http://fastapi_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            location /stub_status {
                stub_status;
                allow all;
            }
        }
    }
