apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          env:
            - name: DATABASE_URL
              # Мы жестко указываем lab-database-postgres, так как база живет в другом приложении Argo
              value: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@lab-database-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.dbName }}"
            - name: REDIS_URL
              # То же самое для Redis
              value: "redis://lab-database-redis:{{ .Values.redis.port }}/0"
          volumeMounts:
            - name: shared-socket
              mountPath: /tmp
        - name: nginx
          image: {{ .Values.nginx.image }}
          volumeMounts:
            - name: shared-socket
              mountPath: /tmp
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: shared-socket
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-config
      # В контейнере backend добавьте жизненный цикл:
      lifecycle:
         postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 5 && chmod 666 /tmp/uvicorn.sock"]
