apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@lab-database-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.dbName }}"
            - name: REDIS_URL
              value: "redis://lab-database-redis:{{ .Values.redis.port }}/0"
          volumeMounts:
            - name: shared-socket
              mountPath: /tmp
        - name: nginx
          image: {{ .Values.nginx.image }}
          volumeMounts:
            - name: shared-socket
              mountPath: /tmp
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: shared-socket
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80          # Порт внутри кластера
      targetPort: 80    # Порт, который слушает Nginx
      nodePort: 30081   # Внешний порт для доступа из браузера
